name: Build Power BI Visual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install PowerBI Visual Tools
      run: npm install -g powerbi-visuals-tools
    - name: Build visual
      run: pbiviz package
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pbiviz
        path: dist/*.pbiviz
